
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5uaWNrMyIsImlkIjoiNWFkZjg2ZWZmZDU0YTBkZmIxNTY1MjVmIiwiaWF0IjoxNTI0NTk4NjQyfQ.hys3Ttd1q82DMfp3KjfrG7Y7Ir9GtmANnlaGh0L6QCc

{
	"title": "A Midsummer Night's Dream",
	"author": "Shakespeare",
	"url" : "http://altavista.com221",
	"likes": 15
}